"""postgresql baseline

Revision ID: 20260814_0001
Revises:
Create Date: 2026-08-14 11:42:36.025741
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260814_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("user_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("register_ts", sa.BigInteger(), nullable=True),
        sa.Column("gender", sa.SmallInteger(), nullable=True),
        sa.Column("login_frequency", sa.SmallInteger(), nullable=True),
        sa.Column("follower_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "followed_topic_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("answer_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("question_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("comment_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "thanks_received_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "likes_received_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("province", sa.String(length=64), nullable=True),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column(
            "followed_topic_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_demo_user", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "source", sa.String(length=32), server_default=sa.text("'mind_small'"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_app_user")),
        comment="MIND-derived demo users and compatibility records.",
    )
    op.create_table(
        "auth_user_id_sequence",
        sa.Column("sequence_key", sa.String(length=64), nullable=False),
        sa.Column("next_user_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("sequence_key", name=op.f("pk_auth_user_id_sequence")),
        comment="Locked ID allocation for users created by the application.",
    )
    op.execute(
        sa.text(
            "INSERT INTO auth_user_id_sequence (sequence_key, next_user_id) "
            "VALUES ('registered_user', 1000000000)"
        )
    )
    op.create_table(
        "author",
        sa.Column("author_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column(
            "is_excellent_author", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("follower_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "is_excellent_answerer", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "source", sa.String(length=32), server_default=sa.text("'mind_small'"), nullable=False
        ),
        sa.PrimaryKeyConstraint("author_id", name=op.f("pk_author")),
        comment="Source-domain compatibility records.",
    )
    op.create_table(
        "event_outbox",
        sa.Column("outbox_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.String(length=128), nullable=False),
        sa.Column("topic", sa.String(length=255), nullable=False),
        sa.Column("message_key", sa.String(length=255), nullable=False),
        sa.Column("payload_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'publishing', 'published', 'dead')",
            name=op.f("chk_event_outbox_outbox_status"),
        ),
        sa.PrimaryKeyConstraint("outbox_id", name=op.f("pk_event_outbox")),
        sa.UniqueConstraint("event_id", "topic", name="uq_event_outbox_event_topic"),
        comment="Transactional Kafka outbox with at-least-once delivery.",
    )
    op.create_index(
        "idx_event_outbox_ready",
        "event_outbox",
        ["status", "available_at", "outbox_id"],
        unique=False,
    )
    op.create_table(
        "question",
        sa.Column("question_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("create_ts", sa.BigInteger(), nullable=True),
        sa.Column("answer_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("follower_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("invitation_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("comment_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("token_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("topic_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("display_title", sa.String(length=255), nullable=True),
        sa.Column(
            "source", sa.String(length=32), server_default=sa.text("'mind_small'"), nullable=False
        ),
        sa.PrimaryKeyConstraint("question_id", name=op.f("pk_question")),
        comment="Article headline compatibility table.",
    )
    op.create_table(
        "sponsored_campaign",
        sa.Column("campaign_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("campaign_name", sa.String(length=128), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column("start_ts", sa.BigInteger(), nullable=False),
        sa.Column("end_ts", sa.BigInteger(), nullable=False),
        sa.Column("daily_budget_micros", sa.BigInteger(), nullable=False),
        sa.Column(
            "pacing_mode", sa.String(length=16), server_default=sa.text("'even'"), nullable=False
        ),
        sa.Column(
            "frequency_cap_per_user_per_day",
            sa.Integer(),
            server_default=sa.text("2"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "pacing_mode IN ('even', 'asap')", name=op.f("chk_sponsored_campaign_campaign_pacing")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'paused', 'ended')",
            name=op.f("chk_sponsored_campaign_campaign_status"),
        ),
        sa.PrimaryKeyConstraint("campaign_id", name=op.f("pk_sponsored_campaign")),
        comment="Synthetic local sponsored campaigns; not a billing source of truth.",
    )
    op.create_index(
        "idx_sponsored_campaign_status_window",
        "sponsored_campaign",
        ["status", "start_ts", "end_ts"],
        unique=False,
    )
    op.create_table(
        "system_profile_seed",
        sa.Column("seed_key", sa.String(length=64), nullable=False),
        sa.Column("topic_weights_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "recent_clicked_answers_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("recent_queries_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "behavior_score", sa.DOUBLE_PRECISION(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("seed_key", name=op.f("pk_system_profile_seed")),
        comment="Reusable cold-start or bootstrap profile seeds.",
    )
    op.create_table(
        "topic",
        sa.Column("topic_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("answer_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("question_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "source", sa.String(length=32), server_default=sa.text("'mind_small'"), nullable=False
        ),
        sa.PrimaryKeyConstraint("topic_id", name=op.f("pk_topic")),
        comment="News category dimension.",
    )
    op.create_table(
        "worker_heartbeat",
        sa.Column("worker_name", sa.String(length=64), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_progress_at", sa.DateTime(), nullable=True),
        sa.Column("lag_messages", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.PrimaryKeyConstraint("worker_name", name=op.f("pk_worker_heartbeat")),
        comment="Readiness heartbeat and progress state for local Kafka workers.",
    )
    op.create_table(
        "answer",
        sa.Column("answer_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("question_id", sa.BigInteger(), nullable=True),
        sa.Column("author_id", sa.BigInteger(), nullable=True),
        sa.Column("is_anonymous", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_high_value", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "is_editor_recommended", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("create_ts", sa.BigInteger(), nullable=True),
        sa.Column("has_picture", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("has_video", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("thanks_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("likes_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("comment_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("collection_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("dislike_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("report_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("helpless_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("token_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("topic_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("display_summary", sa.Text(), nullable=True),
        sa.Column("vector_key", sa.String(length=128), nullable=True),
        sa.Column(
            "is_demo_selected", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("hot_score", sa.DOUBLE_PRECISION(), server_default=sa.text("0"), nullable=False),
        sa.Column("click_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("impression_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "source", sa.String(length=32), server_default=sa.text("'mind_small'"), nullable=False
        ),
        sa.ForeignKeyConstraint(["author_id"], ["author.author_id"], name="fk_answer_author"),
        sa.ForeignKeyConstraint(
            ["question_id"], ["question.question_id"], name="fk_answer_question"
        ),
        sa.PrimaryKeyConstraint("answer_id", name=op.f("pk_answer")),
        comment="Main recommendation entity for the project.",
    )
    op.create_index("idx_answer_author", "answer", ["author_id"], unique=False)
    op.create_index("idx_answer_hot_score", "answer", ["hot_score"], unique=False)
    op.create_index("idx_answer_question", "answer", ["question_id"], unique=False)
    op.create_table(
        "event_idempotency",
        sa.Column("external_event_id", sa.String(length=128), nullable=False),
        sa.Column("payload_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.user_id"], name="fk_event_idempotency_user"
        ),
        sa.PrimaryKeyConstraint("external_event_id", name=op.f("pk_event_idempotency")),
        comment="Atomic claim table for retry-safe event processing.",
    )
    op.create_index(
        "idx_event_idempotency_user_created",
        "event_idempotency",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "feed_request",
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("page_size", sa.Integer(), nullable=False),
        sa.Column("debug", sa.Boolean(), nullable=False),
        sa.Column("include_sponsored", sa.Boolean(), nullable=False),
        sa.Column("experiment_arm", sa.String(length=64), nullable=False),
        sa.Column("as_of_ts", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.user_id"], name="fk_feed_request_user"),
        sa.PrimaryKeyConstraint("request_id", name=op.f("pk_feed_request")),
        comment="Idempotency claim for feed loads that may reserve sponsored delivery.",
    )
    op.create_index(
        "idx_feed_request_user_created", "feed_request", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "query_topic_map",
        sa.Column("query_key", sa.String(length=512), nullable=False),
        sa.Column("display_query", sa.String(length=255), nullable=True),
        sa.Column("query_tokens_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("topic_id", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column(
            "evidence_query_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("evidence_user_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("match_rank", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "source_method",
            sa.String(length=64),
            server_default=sa.text("'offline_user_topic_cooccurrence'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.topic_id"], name="fk_query_topic_topic"),
        sa.PrimaryKeyConstraint("query_key", "topic_id", name=op.f("pk_query_topic_map")),
        comment="English query aliases and category mappings.",
    )
    op.create_index(
        "idx_query_topic_rank", "query_topic_map", ["query_key", "match_rank"], unique=False
    )
    op.create_index("idx_query_topic_topic", "query_topic_map", ["topic_id"], unique=False)
    op.create_table(
        "question_topic",
        sa.Column("question_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=False),
        sa.Column("source_rank", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["question.question_id"], name="fk_question_topic_question"
        ),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.topic_id"], name="fk_question_topic_topic"),
        sa.PrimaryKeyConstraint("question_id", "topic_id", name=op.f("pk_question_topic")),
        comment="Many-to-many bridge between questions and topics.",
    )
    op.create_index("idx_question_topic_topic", "question_topic", ["topic_id"], unique=False)
    op.create_table(
        "sponsored_campaign_daily_state",
        sa.Column("campaign_id", sa.BigInteger(), nullable=False),
        sa.Column("budget_date", sa.Date(), nullable=False),
        sa.Column(
            "expected_spend_micros", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "served_impression_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "confirmed_impression_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("click_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["sponsored_campaign.campaign_id"],
            name="fk_sponsored_daily_state_campaign",
        ),
        sa.PrimaryKeyConstraint(
            "campaign_id", "budget_date", name=op.f("pk_sponsored_campaign_daily_state")
        ),
        comment="Daily synthetic expected-spend and delivery counters.",
    )
    op.create_table(
        "sponsored_campaign_topic",
        sa.Column("campaign_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["sponsored_campaign.campaign_id"],
            name="fk_sponsored_campaign_topic_campaign",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topic.topic_id"], name="fk_sponsored_campaign_topic_topic"
        ),
        sa.PrimaryKeyConstraint(
            "campaign_id", "topic_id", name=op.f("pk_sponsored_campaign_topic")
        ),
        comment="Normalized topic eligibility for sponsored campaigns.",
    )
    op.create_index(
        "idx_sponsored_campaign_topic_topic", "sponsored_campaign_topic", ["topic_id"], unique=False
    )
    op.create_table(
        "sponsored_user_daily_frequency",
        sa.Column("campaign_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("budget_date", sa.Date(), nullable=False),
        sa.Column(
            "served_impression_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_served_ts", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["sponsored_campaign.campaign_id"],
            name="fk_sponsored_frequency_campaign",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.user_id"], name="fk_sponsored_frequency_user"
        ),
        sa.PrimaryKeyConstraint(
            "campaign_id", "user_id", "budget_date", name=op.f("pk_sponsored_user_daily_frequency")
        ),
        comment="Per-user daily sponsored frequency-cap state.",
    )
    op.create_index(
        "idx_sponsored_frequency_user_date",
        "sponsored_user_daily_frequency",
        ["user_id", "budget_date"],
        unique=False,
    )
    op.create_table(
        "user_account",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.user_id"], name="fk_user_account_user"),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_account")),
        sa.UniqueConstraint("email", name="uq_user_account_email"),
        comment="Login credentials linked one-to-one with recommendation users.",
    )
    op.create_table(
        "user_profile",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "cold_start_seed_key",
            sa.String(length=64),
            server_default=sa.text("'cold_start_default'"),
            nullable=False,
        ),
        sa.Column("topic_weights_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "recent_clicked_answers_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("recent_queries_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "behavior_score", sa.DOUBLE_PRECISION(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("user_vector_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("last_event_ts", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cold_start_seed_key"], ["system_profile_seed.seed_key"], name="fk_user_profile_seed"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.user_id"], name="fk_user_profile_user"),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profile")),
        comment="Single-table user profile storage.",
    )
    op.create_index("idx_user_profile_seed", "user_profile", ["cold_start_seed_key"], unique=False)
    op.create_table(
        "answer_topic",
        sa.Column("answer_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=False),
        sa.Column("source_rank", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(["answer_id"], ["answer.answer_id"], name="fk_answer_topic_answer"),
        sa.ForeignKeyConstraint(["topic_id"], ["topic.topic_id"], name="fk_answer_topic_topic"),
        sa.PrimaryKeyConstraint("answer_id", "topic_id", name=op.f("pk_answer_topic")),
        comment="Many-to-many bridge between answers and topics.",
    )
    op.create_index("idx_answer_topic_topic", "answer_topic", ["topic_id"], unique=False)
    op.create_table(
        "hot_answer_snapshot",
        sa.Column("snapshot_key", sa.String(length=64), nullable=False),
        sa.Column("rank_position", sa.Integer(), nullable=False),
        sa.Column("answer_id", sa.BigInteger(), nullable=False),
        sa.Column("hot_score", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("click_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("impression_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "source_window",
            sa.String(length=64),
            server_default=sa.text("'selected_mind_impressions'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"], ["answer.answer_id"], name="fk_hot_answer_snapshot_answer"
        ),
        sa.PrimaryKeyConstraint(
            "snapshot_key", "rank_position", name=op.f("pk_hot_answer_snapshot")
        ),
        sa.UniqueConstraint("snapshot_key", "answer_id", name="uq_hot_snapshot_answer"),
        comment="Fallback pool for hot articles.",
    )
    op.create_index("idx_hot_answer_answer", "hot_answer_snapshot", ["answer_id"], unique=False)
    op.create_table(
        "sponsored_creative",
        sa.Column("creative_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("campaign_id", sa.BigInteger(), nullable=False),
        sa.Column("answer_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("bid_micros", sa.BigInteger(), nullable=False),
        sa.Column("predicted_ctr", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("quality_score", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused')", name=op.f("chk_sponsored_creative_creative_status")
        ),
        sa.CheckConstraint("bid_micros > 0", name=op.f("chk_sponsored_creative_bid")),
        sa.CheckConstraint(
            "predicted_ctr >= 0 AND predicted_ctr <= 1", name=op.f("chk_sponsored_creative_ctr")
        ),
        sa.CheckConstraint(
            "quality_score >= 0 AND quality_score <= 1", name=op.f("chk_sponsored_creative_quality")
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"], ["answer.answer_id"], name="fk_sponsored_creative_answer"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["sponsored_campaign.campaign_id"],
            name="fk_sponsored_creative_campaign",
        ),
        sa.PrimaryKeyConstraint("creative_id", name=op.f("pk_sponsored_creative")),
        sa.UniqueConstraint(
            "campaign_id", "answer_id", name="uq_sponsored_creative_campaign_answer"
        ),
        comment="Sponsored creatives backed by existing answer cards.",
    )
    op.create_index(
        "idx_sponsored_creative_answer", "sponsored_creative", ["answer_id"], unique=False
    )
    op.create_table(
        "sponsored_delivery",
        sa.Column("delivery_id", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("campaign_id", sa.BigInteger(), nullable=False),
        sa.Column("creative_id", sa.BigInteger(), nullable=False),
        sa.Column("answer_id", sa.BigInteger(), nullable=False),
        sa.Column("slot_position", sa.SmallInteger(), nullable=False),
        sa.Column("budget_date", sa.Date(), nullable=False),
        sa.Column("expected_spend_micros", sa.BigInteger(), nullable=False),
        sa.Column("served_ts", sa.BigInteger(), nullable=False),
        sa.Column("confirmed_impression_ts", sa.BigInteger(), nullable=True),
        sa.Column("clicked_ts", sa.BigInteger(), nullable=True),
        sa.Column(
            "delivery_status",
            sa.String(length=16),
            server_default=sa.text("'served'"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.CheckConstraint(
            "delivery_status IN ('served', 'confirmed', 'clicked')",
            name=op.f("chk_sponsored_delivery_delivery_status"),
        ),
        sa.ForeignKeyConstraint(
            ["answer_id"], ["answer.answer_id"], name="fk_sponsored_delivery_answer"
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["sponsored_campaign.campaign_id"],
            name="fk_sponsored_delivery_campaign",
        ),
        sa.ForeignKeyConstraint(
            ["creative_id"],
            ["sponsored_creative.creative_id"],
            name="fk_sponsored_delivery_creative",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.user_id"], name="fk_sponsored_delivery_user"
        ),
        sa.PrimaryKeyConstraint("delivery_id", name=op.f("pk_sponsored_delivery")),
        sa.UniqueConstraint(
            "request_id", "creative_id", name="uq_sponsored_delivery_request_creative"
        ),
        comment="Server-side sponsored serving ledger and client confirmation state.",
    )
    op.create_index(
        "idx_sponsored_delivery_campaign_ts",
        "sponsored_delivery",
        ["campaign_id", "served_ts"],
        unique=False,
    )
    op.create_index(
        "idx_sponsored_delivery_user_ts",
        "sponsored_delivery",
        ["user_id", "served_ts"],
        unique=False,
    )
    op.create_table(
        "user_event",
        sa.Column("event_id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("external_event_id", sa.String(length=128), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("answer_id", sa.BigInteger(), nullable=True),
        sa.Column("sponsored_delivery_id", sa.String(length=128), nullable=True),
        sa.Column("campaign_id", sa.BigInteger(), nullable=True),
        sa.Column("creative_id", sa.BigInteger(), nullable=True),
        sa.Column("query_key", sa.String(length=512), nullable=True),
        sa.Column("query_tokens_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("topic_ids_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "surface", sa.String(length=32), server_default=sa.text("'feed'"), nullable=False
        ),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("dwell_ms", sa.BigInteger(), nullable=True),
        sa.Column(
            "derived_from_raw", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "source_confidence",
            sa.String(length=16),
            server_default=sa.text("'not_applicable'"),
            nullable=False,
        ),
        sa.Column("event_ts", sa.BigInteger(), nullable=False),
        sa.Column("debug_payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "event_type IN ('search_query', 'recommendation_click', 'search_result_click', 'feed_impression', 'detail_view', 'dwell', 'upvote', 'downvote', 'share')",
            name=op.f("chk_user_event_event_type"),
        ),
        sa.CheckConstraint(
            "source_confidence IN ('confirmed', 'heuristic', 'not_applicable')",
            name=op.f("chk_user_event_source_confidence"),
        ),
        sa.ForeignKeyConstraint(["answer_id"], ["answer.answer_id"], name="fk_user_event_answer"),
        sa.ForeignKeyConstraint(
            ["campaign_id"], ["sponsored_campaign.campaign_id"], name="fk_user_event_campaign"
        ),
        sa.ForeignKeyConstraint(
            ["creative_id"], ["sponsored_creative.creative_id"], name="fk_user_event_creative"
        ),
        sa.ForeignKeyConstraint(
            ["sponsored_delivery_id"],
            ["sponsored_delivery.delivery_id"],
            name="fk_user_event_sponsored_delivery",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.user_id"], name="fk_user_event_user"),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_user_event")),
        sa.UniqueConstraint("external_event_id", name="uq_user_event_external_event_id"),
        comment="Event log for closed-loop updates and replay.",
    )
    op.create_index("idx_user_event_answer", "user_event", ["answer_id"], unique=False)
    op.create_index(
        "idx_user_event_campaign_ts", "user_event", ["campaign_id", "event_ts"], unique=False
    )
    op.create_index(
        "idx_user_event_request_answer", "user_event", ["request_id", "answer_id"], unique=False
    )
    op.create_index(
        "idx_user_event_type_ts", "user_event", ["event_type", "event_ts"], unique=False
    )
    op.create_index("idx_user_event_user_ts", "user_event", ["user_id", "event_ts"], unique=False)
    op.execute(
        sa.text(
            """
            CREATE FUNCTION newsrec_set_updated_at() RETURNS trigger AS $$
            BEGIN
                NEW.updated_at = CURRENT_TIMESTAMP;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
            """
        )
    )
    for table_name in (
        "user_account",
        "user_profile",
        "sponsored_campaign",
        "sponsored_creative",
        "sponsored_campaign_daily_state",
        "sponsored_user_daily_frequency",
        "sponsored_delivery",
        "event_outbox",
        "worker_heartbeat",
    ):
        op.execute(
            sa.text(
                f"CREATE TRIGGER trg_{table_name}_updated_at "
                f"BEFORE UPDATE ON {table_name} FOR EACH ROW "
                "EXECUTE FUNCTION newsrec_set_updated_at()"
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP FUNCTION IF EXISTS newsrec_set_updated_at() CASCADE"))
    op.drop_index("idx_user_event_user_ts", table_name="user_event")
    op.drop_index("idx_user_event_type_ts", table_name="user_event")
    op.drop_index("idx_user_event_request_answer", table_name="user_event")
    op.drop_index("idx_user_event_campaign_ts", table_name="user_event")
    op.drop_index("idx_user_event_answer", table_name="user_event")
    op.drop_table("user_event")
    op.drop_index("idx_sponsored_delivery_user_ts", table_name="sponsored_delivery")
    op.drop_index("idx_sponsored_delivery_campaign_ts", table_name="sponsored_delivery")
    op.drop_table("sponsored_delivery")
    op.drop_index("idx_sponsored_creative_answer", table_name="sponsored_creative")
    op.drop_table("sponsored_creative")
    op.drop_index("idx_hot_answer_answer", table_name="hot_answer_snapshot")
    op.drop_table("hot_answer_snapshot")
    op.drop_index("idx_answer_topic_topic", table_name="answer_topic")
    op.drop_table("answer_topic")
    op.drop_index("idx_user_profile_seed", table_name="user_profile")
    op.drop_table("user_profile")
    op.drop_table("user_account")
    op.drop_index("idx_sponsored_frequency_user_date", table_name="sponsored_user_daily_frequency")
    op.drop_table("sponsored_user_daily_frequency")
    op.drop_index("idx_sponsored_campaign_topic_topic", table_name="sponsored_campaign_topic")
    op.drop_table("sponsored_campaign_topic")
    op.drop_table("sponsored_campaign_daily_state")
    op.drop_index("idx_question_topic_topic", table_name="question_topic")
    op.drop_table("question_topic")
    op.drop_index("idx_query_topic_topic", table_name="query_topic_map")
    op.drop_index("idx_query_topic_rank", table_name="query_topic_map")
    op.drop_table("query_topic_map")
    op.drop_index("idx_feed_request_user_created", table_name="feed_request")
    op.drop_table("feed_request")
    op.drop_index("idx_event_idempotency_user_created", table_name="event_idempotency")
    op.drop_table("event_idempotency")
    op.drop_index("idx_answer_question", table_name="answer")
    op.drop_index("idx_answer_hot_score", table_name="answer")
    op.drop_index("idx_answer_author", table_name="answer")
    op.drop_table("answer")
    op.drop_table("worker_heartbeat")
    op.drop_table("topic")
    op.drop_table("system_profile_seed")
    op.drop_index("idx_sponsored_campaign_status_window", table_name="sponsored_campaign")
    op.drop_table("sponsored_campaign")
    op.drop_table("question")
    op.drop_index("idx_event_outbox_ready", table_name="event_outbox")
    op.drop_table("event_outbox")
    op.drop_table("author")
    op.drop_table("auth_user_id_sequence")
    op.drop_table("app_user")
    # ### end Alembic commands ###
